-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "esMX")
if not L then return end

--Translation missing 
L["Change the abbreviations used in the tooltip"] = "Change the abbreviations used in the tooltip"
--Translation missing 
L["Characters below this level will not be shown"] = "Characters below this level will not be shown"
--Translation missing 
L["Chatframe Messages"] = "Chatmessages"
--Translation missing 
L["Color names by class"] = "Color names by class"
--Translation missing 
L["Day when weekly caps and lockouts are reset"] = "Day when weekly caps and lockouts are reset"
--Translation missing 
L["DB_VERSION_UPGRADE_PURGE"] = "Purging database because of a structural change. This is to ensure there are now errors caused by data from older versions. You'll have to login with every char again to get its data shown."
--Translation missing 
L["Encounters Left"] = "Encounters Left"
--Translation missing 
L["Free raid color"] = "Free raid color"
--Translation missing 
L["FREE_RAID_DESC"] = "Set the color used to show when a char is free to raid this instance"
--Translation missing 
L["General Settings"] = "General Settings"
--Translation missing 
L["If the character has completed the weekly quest from Archmage Timear in Dalaran"] = "If the character has completed the weekly quest from Archmage Timear in Dalaran"
--Translation missing 
L["If the character has done the 'Victory in Tol Barad' weekly pvp quest"] = "If the character has done the 'Victory in Tol Barad' weekly pvp quest"
--Translation missing 
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "If the character has done the 'Victory in Wintergrasp' weekly pvp quest"
--Translation missing 
L["If the character has Emissary Bounties available"] = "If the character has Emissary Bounties available"
--Translation missing 
L["If the character has gathered crops off their farm today"] = "If the character has gathered crops off their farm today"
--Translation missing 
L["If the character has received the reward for a seasonal boss"] = "If the character has received the reward for a seasonal boss"
--Translation missing 
L["Instance Abbreviations"] = "Instance Abbreviations"
--Translation missing 
L["Minimum Level"] = "Minimum Level"
--Translation missing 
L["No saved raids found"] = "No saved raids found"
--Translation missing 
L["Raid"] = "Raid"
--Translation missing 
L["Regardles of any saved instances"] = "Regardless of any saved instances"
--Translation missing 
L["Saved raid color"] = "Saved raid color"
--Translation missing 
L["SAVED_RAID_DESC"] = "Set the color used to show when a char is already locked out of this instance"
--Translation missing 
L["Show 5-man instances"] = "Show 5-man instances"
--Translation missing 
L["Show all chars"] = "Show all chars"
--Translation missing 
L["Show character realms"] = "Show character realms"
--Translation missing 
L["Show level of your weekly best mythic plus clearance"] = "Show level of your weekly best mythic plus clearance"
--Translation missing 
L["Show minimap button"] = "Show minimap button"
--Translation missing 
L["Show number of Bonus Rolls and whether weekly quest has been completed"] = "Show number of Bonus Rolls and whether weekly quest has been completed"
--Translation missing 
L["Show number of Warforged Seals and whether weekly quest has been completed"] = "Show number of Warforged Seals and whether weekly quest has been completed"
--Translation missing 
L["Show Realm Headers"] = "Show Realm Headers"
--Translation missing 
L["Show the Ailo minimap button"] = "Show the Ailo minimap button"
--Translation missing 
L["SHOW_ENCOUTERS_LEFT_DESC"] = "If an instance still has encounters left, display that number in the cell"
--Translation missing 
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip"
--Translation missing 
L["Tooltip abbreviation used for heroic raids"] = "Tooltip abbreviation used for heroic raids"
--Translation missing 
L["Tooltip abbreviation used for nonheroic raids"] = "Tooltip abbreviation used for nonheroic raids"
--Translation missing 
L["Track Bonus Rolls"] = "Track Bonus Rolls"
--Translation missing 
L["Track Conquest Points"] = "Track Conquest Points"
--Translation missing 
L["Track crops"] = "Track crops"
--Translation missing 
L["Track 'Daily Heroic'"] = "Track 'Daily Heroic Dungeon'"
--Translation missing 
L["Track 'Daily Heroic Scenario'"] = "Track 'Daily Heroic Scenario'"
--Translation missing 
L["Track 'Daily Scenario'"] = "Track 'Daily Scenario'"
--Translation missing 
L["Track Emissary Bounties"] = "Track Emissary Bounties"
--Translation missing 
L["Track Hellbane rares"] = "Track Hellbane rares"
--Translation missing 
L["Track Mythic Plus"] = "Track Mythic Plus"
--Translation missing 
L["Track PvP daily"] = "Track PvP daily"
--Translation missing 
L["Track Raid Finder instances"] = "Track Raid Finder instances"
--Translation missing 
L["Track Seasonal bosses"] = "Track Seasonal bosses"
--Translation missing 
L["Track 'TB Victory'"] = "Track 'TB Victory'"
--Translation missing 
L["Track Valor Points"] = "Track Valor Points"
--Translation missing 
L["Track Warforged Seals"] = "Track Warforged Seals"
--Translation missing 
L["Track 'WG Victory'"] = "Track 'WG Victory'"
--Translation missing 
L["Track World Bosses"] = "Track World Bosses"
--Translation missing 
L["TRACK_CONQUEST_POINTS_DESC"] = "Show a column with the amount of Conquest Points earned this week"
--Translation missing 
L["TRACK_DAILY_HEROIC_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Dungeon' or not"
--Translation missing 
L["TRACK_DAILY_HEROIC_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Scenario' or not"
--Translation missing 
L["TRACK_DAILY_PVP_DESC"] = "Show a column in the tooltip indicating if a character has won a daily battleground"
--Translation missing 
L["TRACK_DAILY_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Scenario' or not"
--Translation missing 
L["TRACK_HELLBANE_RARES_DESC"] = "Track daily kills of |TInterface\\\\Icons\\\\spell_nature_natureswrath:0|tDeathtalon, |TInterface\\\\Icons\\\\Ability_Warrior_SecondWind:0|tTerrorfist, |TInterface\\\\Icons\\\\Spell_Shadow_SummonSuccubus:0|tVengeance and |TInterface\\\\Icons\\\\ability_vehicle_siegeenginecannon:0|tDoomroller."
--Translation missing 
L["TRACK_VALOR_POINTS_DESC"] = "Show a column with the amount of Valor Points earned this week"
--Translation missing 
L["Tracks any raid done through the Raid Finder tool"] = "Tracks any raid done through the Raid Finder tool"
--Translation missing 
L["Tracks any World Bosses from which loot has been collected this week"] = "Tracks any World Bosses from which loot has been collected this week"
--Translation missing 
L["Updating data for current player."] = "Updating data for current player."
--Translation missing 
L["Use !ClassColors"] = "Use !ClassColors"
--Translation missing 
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "Use !ClassColors addon for class colors used to color the names in the tooltip"
--Translation missing 
L["Weekly Dalaran Quest"] = "Weekly Dalaran Quest"
--Translation missing 
L["Weekly reset day"] = "Weekly reset day"
--Translation missing 
L["Wipe Database"] = "Wipe Database"

