-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "frFR")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "Changer les abréviations utilisées dans la bulle d'aide."
--Translation missing 
L["Characters below this level will not be shown"] = "Characters below this level will not be shown"
--Translation missing 
L["Chatframe Messages"] = "Chatmessages"
L["Color names by class"] = "Colorer les noms par classe"
--Translation missing 
L["Day when weekly caps and lockouts are reset"] = "Day when weekly caps and lockouts are reset"
--Translation missing 
L["DB_VERSION_UPGRADE_PURGE"] = "Purging database because of a structural change. This is to ensure there are now errors caused by data from older versions. You'll have to login with every char again to get its data shown."
--Translation missing 
L["Encounters Left"] = "Encounters Left"
L["Free raid color"] = "Couleur des Raid disponibles"
L["FREE_RAID_DESC"] = "Règle la couleur utilisée lorsque le personnage n'a pas fait cette instance"
L["General Settings"] = "Paramètres généraux"
--Translation missing 
L["If the character has completed the weekly quest from Archmage Timear in Dalaran"] = "If the character has completed the weekly quest from Archmage Timear in Dalaran"
L["If the character has done the 'Victory in Tol Barad' weekly pvp quest"] = "Si le personnage a fait la quête PvP hebdomadaire 'Victoire à Tol Barad'"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "Si le personnage a fait la quête PvP hebdomadaire 'Victoire à Joug d'hiver\""
--Translation missing 
L["If the character has Emissary Bounties available"] = "If the character has Emissary Bounties available"
--Translation missing 
L["If the character has gathered crops off their farm today"] = "If the character has gathered crops off their farm today"
--Translation missing 
L["If the character has received the reward for a seasonal boss"] = "If the character has received the reward for a seasonal boss"
L["Instance Abbreviations"] = "Abréviations des instances"
--Translation missing 
L["Minimum Level"] = "Minimum Level"
L["No saved raids found"] = "Aucun Raid effectué n'a été trouvé"
L["Raid"] = true
--Translation missing 
L["Regardles of any saved instances"] = "Regardless of any saved instances"
L["Saved raid color"] = "Couleur des Raid déjà fait"
L["SAVED_RAID_DESC"] = "Règle la couleur utilisée lorsque le personnage a déjà fait cette instance"
L["Show 5-man instances"] = "Montrer les instances à 5"
L["Show all chars"] = "Montrer tous les personnages"
L["Show character realms"] = "Montrer le royaume des personnages."
--Translation missing 
L["Show level of your weekly best mythic plus clearance"] = "Show level of your weekly best mythic plus clearance"
L["Show minimap button"] = "Montrer le bouton de la minicarte"
--Translation missing 
L["Show number of Bonus Rolls and whether weekly quest has been completed"] = "Show number of Bonus Rolls and whether weekly quest has been completed"
--Translation missing 
L["Show number of Warforged Seals and whether weekly quest has been completed"] = "Show number of Warforged Seals and whether weekly quest has been completed"
--Translation missing 
L["Show Realm Headers"] = "Show Realm Headers"
L["Show the Ailo minimap button"] = "Affiche le bouton Ailo sur la minimap"
--Translation missing 
L["SHOW_ENCOUTERS_LEFT_DESC"] = "If an instance still has encounters left, display that number in the cell"
--Translation missing 
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip"
L["Tooltip abbreviation used for heroic raids"] = "Abréviation utilisée pour les raids en mode héroïque"
L["Tooltip abbreviation used for nonheroic raids"] = "Abréviation utilisée pour les raids en mode normal"
--Translation missing 
L["Track Bonus Rolls"] = "Track Bonus Rolls"
--Translation missing 
L["Track Conquest Points"] = "Track Conquest Points"
--Translation missing 
L["Track crops"] = "Track crops"
L["Track 'Daily Heroic'"] = "Suivis des instances héroiques journalières"
--Translation missing 
L["Track 'Daily Heroic Scenario'"] = "Track 'Daily Heroic Scenario'"
--Translation missing 
L["Track 'Daily Scenario'"] = "Track 'Daily Scenario'"
--Translation missing 
L["Track Emissary Bounties"] = "Track Emissary Bounties"
--Translation missing 
L["Track Hellbane rares"] = "Track Hellbane rares"
--Translation missing 
L["Track Mythic Plus"] = "Track Mythic Plus"
L["Track PvP daily"] = "Suivis des quêtes PvP journalières"
--Translation missing 
L["Track Raid Finder instances"] = "Track Raid Finder instances"
--Translation missing 
L["Track Seasonal bosses"] = "Track Seasonal bosses"
L["Track 'TB Victory'"] = "Suivis de la quête 'Victoire à Tol Barad'"
--Translation missing 
L["Track Valor Points"] = "Track Valor Points"
--Translation missing 
L["Track Warforged Seals"] = "Track Warforged Seals"
L["Track 'WG Victory'"] = "Suivis de la quête 'Victoire à Joug d'hiver\""
--Translation missing 
L["Track World Bosses"] = "Track World Bosses"
--Translation missing 
L["TRACK_CONQUEST_POINTS_DESC"] = "Show a column with the amount of Conquest Points earned this week"
--Translation missing 
L["TRACK_DAILY_HEROIC_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Dungeon' or not"
--Translation missing 
L["TRACK_DAILY_HEROIC_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Scenario' or not"
--Translation missing 
L["TRACK_DAILY_PVP_DESC"] = "Show a column in the tooltip indicating if a character has won a daily battleground"
--Translation missing 
L["TRACK_DAILY_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Scenario' or not"
--Translation missing 
L["TRACK_HELLBANE_RARES_DESC"] = "Track daily kills of |TInterface\\\\Icons\\\\spell_nature_natureswrath:0|tDeathtalon, |TInterface\\\\Icons\\\\Ability_Warrior_SecondWind:0|tTerrorfist, |TInterface\\\\Icons\\\\Spell_Shadow_SummonSuccubus:0|tVengeance and |TInterface\\\\Icons\\\\ability_vehicle_siegeenginecannon:0|tDoomroller."
--Translation missing 
L["TRACK_VALOR_POINTS_DESC"] = "Show a column with the amount of Valor Points earned this week"
--Translation missing 
L["Tracks any raid done through the Raid Finder tool"] = "Tracks any raid done through the Raid Finder tool"
--Translation missing 
L["Tracks any World Bosses from which loot has been collected this week"] = "Tracks any World Bosses from which loot has been collected this week"
L["Updating data for current player."] = "Mise à jour des données pour le joueur actuel en cours."
L["Use !ClassColors"] = "Utiliser l'addon !ClassColors"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "Utiliser l'addon !ClassColors pour les couleurs de classe utilisées pour colorer les noms dans l'info-bulle."
--Translation missing 
L["Weekly Dalaran Quest"] = "Weekly Dalaran Quest"
--Translation missing 
L["Weekly reset day"] = "Weekly reset day"
L["Wipe Database"] = "Remise à zéro de la base de données"

