-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "ruRU")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "Изменить сокращения во всплывающих подсказках"
--Translation missing 
L["Characters below this level will not be shown"] = "Characters below this level will not be shown"
L["Chatframe Messages"] = "Сообщения в чате"
L["Color names by class"] = "Имена цветом класса"
--Translation missing 
L["Day when weekly caps and lockouts are reset"] = "Day when weekly caps and lockouts are reset"
L["DB_VERSION_UPGRADE_PURGE"] = "Очищаю БД в связи с изменениями структуры. Необходимо для предотвращения ошибок, связанных с сохраненными данными от предыдущих версий. Вы должны снова зайти в игру всеми персонажами для сбора данных."
--Translation missing 
L["Encounters Left"] = "Encounters Left"
L["Free raid color"] = "Цвет доступных рейдов"
L["FREE_RAID_DESC"] = "Выберите цвет, используемый для отображения доступных рейдов"
L["General Settings"] = "Общие настройки"
--Translation missing 
L["If the character has completed the weekly quest from Archmage Timear in Dalaran"] = "If the character has completed the weekly quest from Archmage Timear in Dalaran"
--Translation missing 
L["If the character has done the 'Victory in Tol Barad' weekly pvp quest"] = "If the character has done the 'Victory in Tol Barad' weekly pvp quest"
--Translation missing 
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "If the character has done the 'Victory in Wintergrasp' weekly pvp quest"
--Translation missing 
L["If the character has Emissary Bounties available"] = "If the character has Emissary Bounties available"
--Translation missing 
L["If the character has gathered crops off their farm today"] = "If the character has gathered crops off their farm today"
--Translation missing 
L["If the character has received the reward for a seasonal boss"] = "If the character has received the reward for a seasonal boss"
L["Instance Abbreviations"] = "Сокращения подземелий"
--Translation missing 
L["Minimum Level"] = "Minimum Level"
L["No saved raids found"] = "Нет сохраненных рейдов"
L["Raid"] = "Рейд"
--Translation missing 
L["Regardles of any saved instances"] = "Regardless of any saved instances"
L["Saved raid color"] = "Цвет сохраненных рейдов"
L["SAVED_RAID_DESC"] = "Выберите цвет, используемый для отображения сохраненных рейдов"
L["Show 5-man instances"] = "Показывать подземелья на 5 игроков"
--Translation missing 
L["Show all chars"] = "Show all chars"
L["Show character realms"] = "Показывать игровой мир персонажа "
--Translation missing 
L["Show level of your weekly best mythic plus clearance"] = "Show level of your weekly best mythic plus clearance"
L["Show minimap button"] = "Показать иконку у мини-карты"
--Translation missing 
L["Show number of Bonus Rolls and whether weekly quest has been completed"] = "Show number of Bonus Rolls and whether weekly quest has been completed"
--Translation missing 
L["Show number of Warforged Seals and whether weekly quest has been completed"] = "Show number of Warforged Seals and whether weekly quest has been completed"
--Translation missing 
L["Show Realm Headers"] = "Show Realm Headers"
L["Show the Ailo minimap button"] = "Закрепить иконку у мини-карты"
--Translation missing 
L["SHOW_ENCOUTERS_LEFT_DESC"] = "If an instance still has encounters left, display that number in the cell"
--Translation missing 
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip"
L["Tooltip abbreviation used for heroic raids"] = "Сокращенное обозначение для героич. рейдов"
L["Tooltip abbreviation used for nonheroic raids"] = "Сокращенное обозначение для нормал рейдов"
--Translation missing 
L["Track Bonus Rolls"] = "Track Bonus Rolls"
--Translation missing 
L["Track Conquest Points"] = "Track Conquest Points"
--Translation missing 
L["Track crops"] = "Track crops"
L["Track 'Daily Heroic'"] = "Отслеживать \"рандомлик\""
--Translation missing 
L["Track 'Daily Heroic Scenario'"] = "Track 'Daily Heroic Scenario'"
--Translation missing 
L["Track 'Daily Scenario'"] = "Track 'Daily Scenario'"
--Translation missing 
L["Track Emissary Bounties"] = "Track Emissary Bounties"
--Translation missing 
L["Track Hellbane rares"] = "Track Hellbane rares"
--Translation missing 
L["Track Mythic Plus"] = "Track Mythic Plus"
--Translation missing 
L["Track PvP daily"] = "Track PvP daily"
--Translation missing 
L["Track Raid Finder instances"] = "Track Raid Finder instances"
--Translation missing 
L["Track Seasonal bosses"] = "Track Seasonal bosses"
--Translation missing 
L["Track 'TB Victory'"] = "Track 'TB Victory'"
--Translation missing 
L["Track Valor Points"] = "Track Valor Points"
--Translation missing 
L["Track Warforged Seals"] = "Track Warforged Seals"
--Translation missing 
L["Track 'WG Victory'"] = "Track 'WG Victory'"
--Translation missing 
L["Track World Bosses"] = "Track World Bosses"
--Translation missing 
L["TRACK_CONQUEST_POINTS_DESC"] = "Show a column with the amount of Conquest Points earned this week"
L["TRACK_DAILY_HEROIC_DESC"] = "Если персонаж сегодня уже выполнил \"Случайное подземелье, героический\" во всплывающей подсказке будет отображаться \"Эмблема Льда\" перед его именем"
--Translation missing 
L["TRACK_DAILY_HEROIC_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Scenario' or not"
--Translation missing 
L["TRACK_DAILY_PVP_DESC"] = "Show a column in the tooltip indicating if a character has won a daily battleground"
--Translation missing 
L["TRACK_DAILY_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Scenario' or not"
--Translation missing 
L["TRACK_HELLBANE_RARES_DESC"] = "Track daily kills of |TInterface\\\\Icons\\\\spell_nature_natureswrath:0|tDeathtalon, |TInterface\\\\Icons\\\\Ability_Warrior_SecondWind:0|tTerrorfist, |TInterface\\\\Icons\\\\Spell_Shadow_SummonSuccubus:0|tVengeance and |TInterface\\\\Icons\\\\ability_vehicle_siegeenginecannon:0|tDoomroller."
--Translation missing 
L["TRACK_VALOR_POINTS_DESC"] = "Show a column with the amount of Valor Points earned this week"
--Translation missing 
L["Tracks any raid done through the Raid Finder tool"] = "Tracks any raid done through the Raid Finder tool"
--Translation missing 
L["Tracks any World Bosses from which loot has been collected this week"] = "Tracks any World Bosses from which loot has been collected this week"
L["Updating data for current player."] = "Обновляю данные для текущего персонажа"
L["Use !ClassColors"] = "Использовать цвета классов"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "Использовать аддон !ClassColors для отображения имени персонажа цветом класса во всплывающей подсказке"
--Translation missing 
L["Weekly Dalaran Quest"] = "Weekly Dalaran Quest"
--Translation missing 
L["Weekly reset day"] = "Weekly reset day"
L["Wipe Database"] = "Очистить БД"

