-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "zhCN")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "更改提示缩写"
--Translation missing 
L["Characters below this level will not be shown"] = "Characters below this level will not be shown"
L["Chatframe Messages"] = "聊天框信息"
L["Color names by class"] = "职业颜色"
L["Day when weekly caps and lockouts are reset"] = "每周重置锁定的日期"
L["DB_VERSION_UPGRADE_PURGE"] = "由于结构变化而清除数据库。当前错误因旧版本数据所造成。必须先登录每个角色再次获得的数据显示。"
L["Encounters Left"] = "剩余首领"
L["Free raid color"] = "可用团队颜色"
L["FREE_RAID_DESC"] = "设置用来显示角色可用团队副本的颜色"
L["General Settings"] = "一般设置"
--Translation missing 
L["If the character has completed the weekly quest from Archmage Timear in Dalaran"] = "If the character has completed the weekly quest from Archmage Timear in Dalaran"
L["If the character has done the 'Victory in Tol Barad' weekly pvp quest"] = "如果角色已完成 '托尔巴拉德的胜利' 每周PvP任务"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "如果角色已完成  '冬拥湖的胜利'  每周PvP任务"
--Translation missing 
L["If the character has Emissary Bounties available"] = "If the character has Emissary Bounties available"
--Translation missing 
L["If the character has gathered crops off their farm today"] = "If the character has gathered crops off their farm today"
L["If the character has received the reward for a seasonal boss"] = "如果角色已收到季节性首领的奖励"
L["Instance Abbreviations"] = "副本缩写"
--Translation missing 
L["Minimum Level"] = "Minimum Level"
L["No saved raids found"] = "没有找到已保存团队"
L["Raid"] = "团队"
L["Regardles of any saved instances"] = "无论任何保存的副本"
L["Saved raid color"] = "已保存团队颜色"
L["SAVED_RAID_DESC"] = "设置用来显示角色已保存团队副本的颜色"
L["Show 5-man instances"] = "显示5人副本"
L["Show all chars"] = "显示所有角色"
L["Show character realms"] = "显示角色服务器"
--Translation missing 
L["Show level of your weekly best mythic plus clearance"] = "Show level of your weekly best mythic plus clearance"
L["Show minimap button"] = "显示迷你地图图标"
--Translation missing 
L["Show number of Bonus Rolls and whether weekly quest has been completed"] = "Show number of Bonus Rolls and whether weekly quest has been completed"
--Translation missing 
L["Show number of Warforged Seals and whether weekly quest has been completed"] = "Show number of Warforged Seals and whether weekly quest has been completed"
L["Show Realm Headers"] = "显示服务器标题"
L["Show the Ailo minimap button"] = "显示 Ailo 迷你地图图标"
L["SHOW_ENCOUTERS_LEFT_DESC"] = "如果副本还有剩余的首领, 则显示剩余数量"
L["SHOW_REALMLINES_DESC"] = "在提示信息开始显示来自其他服务器的角色标题"
L["Tooltip abbreviation used for heroic raids"] = "英雄团队提示缩写"
L["Tooltip abbreviation used for nonheroic raids"] = "非英雄团队提示缩写"
--Translation missing 
L["Track Bonus Rolls"] = "Track Bonus Rolls"
--Translation missing 
L["Track Conquest Points"] = "Track Conquest Points"
--Translation missing 
L["Track crops"] = "Track crops"
L["Track 'Daily Heroic'"] = "追踪 '日常英雄'"
--Translation missing 
L["Track 'Daily Heroic Scenario'"] = "Track 'Daily Heroic Scenario'"
--Translation missing 
L["Track 'Daily Scenario'"] = "Track 'Daily Scenario'"
--Translation missing 
L["Track Emissary Bounties"] = "Track Emissary Bounties"
--Translation missing 
L["Track Hellbane rares"] = "Track Hellbane rares"
--Translation missing 
L["Track Mythic Plus"] = "Track Mythic Plus"
L["Track PvP daily"] = "追踪日常PvP"
L["Track Raid Finder instances"] = "追踪团队寻找器副本"
L["Track Seasonal bosses"] = "追踪季节性首领"
L["Track 'TB Victory'"] = "追踪 '托尔巴拉德的胜利'"
L["Track Valor Points"] = "追踪勇气点数"
--Translation missing 
L["Track Warforged Seals"] = "Track Warforged Seals"
L["Track 'WG Victory'"] = "追踪 '冬拥湖的胜利'"
--Translation missing 
L["Track World Bosses"] = "Track World Bosses"
--Translation missing 
L["TRACK_CONQUEST_POINTS_DESC"] = "Show a column with the amount of Conquest Points earned this week"
L["TRACK_DAILY_HEROIC_DESC"] = "如果角色已经完成今天的 '日常英雄', 将在提示信息中显示一个列来指示"
--Translation missing 
L["TRACK_DAILY_HEROIC_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Scenario' or not"
--Translation missing 
L["TRACK_DAILY_PVP_DESC"] = "Show a column in the tooltip indicating if a character has won a daily battleground"
--Translation missing 
L["TRACK_DAILY_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Scenario' or not"
--Translation missing 
L["TRACK_HELLBANE_RARES_DESC"] = "Track daily kills of |TInterface\\\\Icons\\\\spell_nature_natureswrath:0|tDeathtalon, |TInterface\\\\Icons\\\\Ability_Warrior_SecondWind:0|tTerrorfist, |TInterface\\\\Icons\\\\Spell_Shadow_SummonSuccubus:0|tVengeance and |TInterface\\\\Icons\\\\ability_vehicle_siegeenginecannon:0|tDoomroller."
L["TRACK_VALOR_POINTS_DESC"] = "追踪角色可以通过英雄副本来获得150点勇气点数的次数"
L["Tracks any raid done through the Raid Finder tool"] = "追踪任何通过团队寻找器工具完成的团队副本"
--Translation missing 
L["Tracks any World Bosses from which loot has been collected this week"] = "Tracks any World Bosses from which loot has been collected this week"
L["Updating data for current player."] = "更新当前角色数据"
L["Use !ClassColors"] = "使用 !ClassColors"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "提示使用 !ClassColors 插件的职业颜色"
--Translation missing 
L["Weekly Dalaran Quest"] = "Weekly Dalaran Quest"
L["Weekly reset day"] = "每周重置日期"
L["Wipe Database"] = "灭团数据库"

