-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "zhTW")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "修改簡稱"
--Translation missing 
L["Characters below this level will not be shown"] = "Characters below this level will not be shown"
L["Chatframe Messages"] = "對話框訊息"
L["Color names by class"] = "角色名稱依職業著色"
--Translation missing 
L["Day when weekly caps and lockouts are reset"] = "Day when weekly caps and lockouts are reset"
L["DB_VERSION_UPGRADE_PURGE"] = "系統已更新，為確保舊版資料造成UI錯誤，將清空舊版資料庫."
L["Encounters Left"] = "剩餘首領"
L["Free raid color"] = "無進度顏色"
L["FREE_RAID_DESC"] = "設定角色在該副本沒有進度時的顯示顏色"
L["General Settings"] = "一般設定"
--Translation missing 
L["If the character has completed the weekly quest from Archmage Timear in Dalaran"] = "If the character has completed the weekly quest from Archmage Timear in Dalaran"
L["If the character has done the 'Victory in Tol Barad' weekly pvp quest"] = "追蹤托巴拉德每週任務:托巴拉德的勝利是否完成"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "追蹤冬握湖每週任務:冬握湖勝利是否完成"
--Translation missing 
L["If the character has Emissary Bounties available"] = "If the character has Emissary Bounties available"
--Translation missing 
L["If the character has gathered crops off their farm today"] = "If the character has gathered crops off their farm today"
--Translation missing 
L["If the character has received the reward for a seasonal boss"] = "If the character has received the reward for a seasonal boss"
L["Instance Abbreviations"] = "副本簡稱"
--Translation missing 
L["Minimum Level"] = "Minimum Level"
L["No saved raids found"] = "沒有任何團隊記錄"
L["Raid"] = "團隊"
L["Regardles of any saved instances"] = "忽略已儲存的副本進度"
L["Saved raid color"] = "有進度顏色"
L["SAVED_RAID_DESC"] = "設定角色已有該副本進度時的顯示顏色"
L["Show 5-man instances"] = "顯示五人副本進度"
L["Show all chars"] = "顯示所有角色"
L["Show character realms"] = "顯示角色所在伺服器"
--Translation missing 
L["Show level of your weekly best mythic plus clearance"] = "Show level of your weekly best mythic plus clearance"
L["Show minimap button"] = "顯示小地圖按鈕"
--Translation missing 
L["Show number of Bonus Rolls and whether weekly quest has been completed"] = "Show number of Bonus Rolls and whether weekly quest has been completed"
--Translation missing 
L["Show number of Warforged Seals and whether weekly quest has been completed"] = "Show number of Warforged Seals and whether weekly quest has been completed"
L["Show Realm Headers"] = "顯示伺服器名稱"
L["Show the Ailo minimap button"] = "顯示小地圖按鈕"
L["SHOW_ENCOUTERS_LEFT_DESC"] = "顯示團隊進度剩餘的首領數量"
L["SHOW_REALMLINES_DESC"] = "在不同伺服器角色前顯示伺服器名稱"
L["Tooltip abbreviation used for heroic raids"] = "英雄模式簡稱"
L["Tooltip abbreviation used for nonheroic raids"] = "普通模式簡稱"
--Translation missing 
L["Track Bonus Rolls"] = "Track Bonus Rolls"
--Translation missing 
L["Track Conquest Points"] = "Track Conquest Points"
--Translation missing 
L["Track crops"] = "Track crops"
L["Track 'Daily Heroic'"] = "追蹤每日英雄進度"
--Translation missing 
L["Track 'Daily Heroic Scenario'"] = "Track 'Daily Heroic Scenario'"
L["Track 'Daily Scenario'"] = "追蹤 '每日事件'"
--Translation missing 
L["Track Emissary Bounties"] = "Track Emissary Bounties"
--Translation missing 
L["Track Hellbane rares"] = "Track Hellbane rares"
--Translation missing 
L["Track Mythic Plus"] = "Track Mythic Plus"
L["Track PvP daily"] = "追蹤每日隨機戰場"
--Translation missing 
L["Track Raid Finder instances"] = "Track Raid Finder instances"
L["Track Seasonal bosses"] = "追蹤節慶首領"
L["Track 'TB Victory'"] = "追蹤每週:托巴拉德的勝利"
L["Track Valor Points"] = "追蹤勇氣點數"
--Translation missing 
L["Track Warforged Seals"] = "Track Warforged Seals"
L["Track 'WG Victory'"] = "追蹤每週:冬握湖勝利"
--Translation missing 
L["Track World Bosses"] = "Track World Bosses"
--Translation missing 
L["TRACK_CONQUEST_POINTS_DESC"] = "Show a column with the amount of Conquest Points earned this week"
L["TRACK_DAILY_HEROIC_DESC"] = "追蹤每日隨機英雄副本是否完成"
--Translation missing 
L["TRACK_DAILY_HEROIC_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic Scenario' or not"
--Translation missing 
L["TRACK_DAILY_PVP_DESC"] = "Show a column in the tooltip indicating if a character has won a daily battleground"
--Translation missing 
L["TRACK_DAILY_SCENARIO_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Scenario' or not"
--Translation missing 
L["TRACK_HELLBANE_RARES_DESC"] = "Track daily kills of |TInterface\\\\Icons\\\\spell_nature_natureswrath:0|tDeathtalon, |TInterface\\\\Icons\\\\Ability_Warrior_SecondWind:0|tTerrorfist, |TInterface\\\\Icons\\\\Spell_Shadow_SummonSuccubus:0|tVengeance and |TInterface\\\\Icons\\\\ability_vehicle_siegeenginecannon:0|tDoomroller."
--Translation missing 
L["TRACK_VALOR_POINTS_DESC"] = "Show a column with the amount of Valor Points earned this week"
--Translation missing 
L["Tracks any raid done through the Raid Finder tool"] = "Tracks any raid done through the Raid Finder tool"
--Translation missing 
L["Tracks any World Bosses from which loot has been collected this week"] = "Tracks any World Bosses from which loot has been collected this week"
L["Updating data for current player."] = "更新當前角色資訊"
L["Use !ClassColors"] = "使用職業顏色"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "將角色名稱依職業顯示不同顏色"
--Translation missing 
L["Weekly Dalaran Quest"] = "Weekly Dalaran Quest"
--Translation missing 
L["Weekly reset day"] = "Weekly reset day"
L["Wipe Database"] = "清除資料庫"

